### ISSUE TITLE
Prblm

### ISSUE THREAD

**Issue by ALBINPRAVEEN** [moshe-coh/Terminal-Bot#3]
how to  run sudo commands
also cannot dwnload packages

**Comment by moshe-coh** [comment]
If you run the robot on heroku I think it is not possible to run there suod commnds, on vps servers it is possible!

**Comment by ALBINPRAVEEN** [comment]
vps also not yet working 
sudo commands dead

**Comment by moshe-coh** [comment]
Please send a screenshot or the error!
