### ISSUE TITLE
Project asks for Client Credentials While only Bot Token should be required

### ISSUE THREAD

**Issue by AllesWasTaken** [moshe-coh/Terminal-Bot#4]
this project asks in the config.py and in the video tutorial to input a client account credentials via the APP_ID and API_HASH , in reality this shouldnt be a requirement because the only thing needed should be the bot Token, this project uses Pyrogram as a telegram implementation, Client Side credentials arent needed to work with bots and its just a useless and possible risky information to give away. please address this issue and delete the need to input these 2 informations

**Comment by moshe-coh** [comment]
Because the connection of program to the telegram API is MTProto - robots also need API ID & API HASH.
Feel free to read the documentation of program!
