### ISSUE TITLE
App_id  = int( os.environ.get("ID") ) returns error as " os.environ.get("ID") " returns None type

### ISSUE THREAD

**Issue by chvsain9** [moshe-coh/Terminal-Bot#8]
hi  i tried giving the app id as integer directly to the App_id variable but im getting NO API KEY FOUND in a virtual machine

i think there is a bug in the case of vps as  " os.environ.get("ID") " returns None type

**Comment by moshe-coh** [comment]
hi. 
If you have a VPS you need to configure it as follows:
os.environ.get("APP_ID", 123456)
